repos:
  - repo: https://github.com/pycqa/isort
    rev: "5.12.0"
    hooks:
      - id: isort
        args:
          - "--profile=black"
          - "-l 88"
          - "--extend-skip-glob=alembic/**"
  - repo: https://github.com/ambv/black
    rev: "23.10.1"
    hooks:
      - id: black
        language_version: python3
        args:
          - "--exclude=alembic/**"
  - repo: https://github.com/pycqa/flake8
    rev: "6.1.0"
    hooks:
      - id: flake8
        args:
          - "--exclude=alembic/**"
          - "--max-line-length=88"
          - "--per-file-ignores=*/__init__.py:F401,F403,tests/**.py:F401,F811"
          - "--extend-ignore=E203,W503"
