version: "3.9"
services:
  db:
    image: postgres:13.3-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./data:/db/conf/
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 1s
      timeout: 3s
      retries: 30

  api:
    build: .
    command: pipenv run uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - .:/api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  minio:
      image: quay.io/minio/minio:latest
      env_file:
        - .env
      environment:
        MINIO_ROOT_USER: ${ACCESS_KEY}
        MINIO_ROOT_PASSWORD: ${SECRET_ACCESS_KEY}
      command: server --console-address ":9001" /data
      ports:
        - '9000:9000'
        - '9001:9001'

volumes:
  dbdata: null
