"""fix_blog_thumbnail

Revision ID: 12dcbfb2cedf
Revises: 37f656010f1c
Create Date: 2023-11-24 09:07:27.489551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12dcbfb2cedf'
down_revision = '37f656010f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'thumbnail_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('thumbnail_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
