"""create_blog

Revision ID: 37f656010f1c
Revises: c3bb170e276e
Create Date: 2023-11-22 00:04:26.584146

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '37f656010f1c'
down_revision = 'c3bb170e276e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('thumbnail_url', sa.String(), nullable=False),
    sa.Column('body_text', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('visibility', postgresql.ENUM(name='visibility', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_assets',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('blog_id', sa.String(length=255), nullable=True),
    sa.Column('asset_type', sa.Enum('image', 'video', name='blogassettype'), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('extension', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_favorites',
    sa.Column('blog_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blog_id', 'user_id')
    )
    op.create_table('blog_tagging',
    sa.Column('blog_id', sa.String(length=255), nullable=False),
    sa.Column('tag_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blog_id', 'tag_id')
    )
    op.create_table('blog_thumbnails',
    sa.Column('blog_id', sa.String(length=255), nullable=False),
    sa.Column('asset_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['blog_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blog_id', 'asset_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_thumbnails')
    op.drop_table('blog_tagging')
    op.drop_table('blog_favorites')
    op.drop_table('blog_assets')
    op.drop_table('blogs')
    sa.Enum('image', 'video', name='blogassettype').drop(op.get_bind())
    # ### end Alembic commands ###
