"""extensionのスペルミス修正

Revision ID: 543bc3330fe5
Revises: cf50f054281b
Create Date: 2022-09-23 21:07:39.766930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543bc3330fe5'
down_revision = 'cf50f054281b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('extension', sa.String(length=255), nullable=True))
    op.drop_column('asset', 'extention')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('extention', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('asset', 'extension')
    # ### end Alembic commands ###
