"""add asset extention

Revision ID: 7b9de5af9c12
Revises: ebd30ecf2473
Create Date: 2022-02-27 10:41:51.568298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b9de5af9c12'
down_revision = 'ebd30ecf2473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
