"""add_favorite_table

Revision ID: ab63d309c996
Revises: fb88809c383b
Create Date: 2022-10-28 19:03:19.077058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab63d309c996'
down_revision = 'fb88809c383b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
