"""foreignkey_cascade

Revision ID: c3bb170e276e
Revises: 3a98fa6461c5
Create Date: 2023-07-15 04:13:23.929944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3bb170e276e'
down_revision = '3a98fa6461c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('asset_work_id_fkey', 'asset', type_='foreignkey')
    op.create_foreign_key(None, 'asset', 'works', ['work_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('comment_work_id_fkey', 'comment', type_='foreignkey')
    op.drop_constraint('comment_user_id_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'comment', 'works', ['work_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('favorite_user_id_fkey', 'favorite', type_='foreignkey')
    op.drop_constraint('favorite_work_id_fkey', 'favorite', type_='foreignkey')
    op.create_foreign_key(None, 'favorite', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'favorite', 'works', ['work_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('taggings_work_id_fkey', 'taggings', type_='foreignkey')
    op.drop_constraint('taggings_tag_id_fkey', 'taggings', type_='foreignkey')
    op.create_foreign_key(None, 'taggings', 'works', ['work_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'taggings', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('thumbnails_asset_id_fkey', 'thumbnails', type_='foreignkey')
    op.drop_constraint('thumbnails_work_id_fkey', 'thumbnails', type_='foreignkey')
    op.create_foreign_key(None, 'thumbnails', 'asset', ['asset_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'thumbnails', 'works', ['work_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('token_user_id_fkey', 'token', type_='foreignkey')
    op.create_foreign_key(None, 'token', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('urlinfo_work_id_fkey', 'urlinfo', type_='foreignkey')
    op.create_foreign_key(None, 'urlinfo', 'works', ['work_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('works_user_id_fkey', 'works', type_='foreignkey')
    op.create_foreign_key(None, 'works', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'works', type_='foreignkey')
    op.create_foreign_key('works_user_id_fkey', 'works', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'urlinfo', type_='foreignkey')
    op.create_foreign_key('urlinfo_work_id_fkey', 'urlinfo', 'works', ['work_id'], ['id'])
    op.drop_constraint(None, 'token', type_='foreignkey')
    op.create_foreign_key('token_user_id_fkey', 'token', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'thumbnails', type_='foreignkey')
    op.drop_constraint(None, 'thumbnails', type_='foreignkey')
    op.create_foreign_key('thumbnails_work_id_fkey', 'thumbnails', 'works', ['work_id'], ['id'])
    op.create_foreign_key('thumbnails_asset_id_fkey', 'thumbnails', 'asset', ['asset_id'], ['id'])
    op.drop_constraint(None, 'taggings', type_='foreignkey')
    op.drop_constraint(None, 'taggings', type_='foreignkey')
    op.create_foreign_key('taggings_tag_id_fkey', 'taggings', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key('taggings_work_id_fkey', 'taggings', 'works', ['work_id'], ['id'])
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.create_foreign_key('favorite_work_id_fkey', 'favorite', 'works', ['work_id'], ['id'])
    op.create_foreign_key('favorite_user_id_fkey', 'favorite', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_user_id_fkey', 'comment', 'user', ['user_id'], ['id'])
    op.create_foreign_key('comment_work_id_fkey', 'comment', 'works', ['work_id'], ['id'])
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.create_foreign_key('asset_work_id_fkey', 'asset', 'works', ['work_id'], ['id'])
    # ### end Alembic commands ###
