"""add asset extention

Revision ID: cf50f054281b
Revises: ebd30ecf2473
Create Date: 2022-02-27 10:49:53.076606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf50f054281b'
down_revision = 'ebd30ecf2473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('extention', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'extention')
    # ### end Alembic commands ###
