"""blog_published_at

Revision ID: e58d86da425a
Revises: 12dcbfb2cedf
Create Date: 2023-12-06 21:25:09.057104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e58d86da425a'
down_revision = '12dcbfb2cedf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('published_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'published_at')
    # ### end Alembic commands ###
