"""test add table

Revision ID: ebd30ecf2473
Revises: 
Create Date: 2021-11-20 13:21:20.274519

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ebd30ecf2473'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('twitter_id', sa.String(), nullable=True))
    op.add_column('user', sa.Column('github_id', sa.String(), nullable=True))
    op.add_column('works', sa.Column('visibility', sa.Enum('public', 'private', 'draft', name='visibility'), nullable=True))
    op.drop_column('works', 'visibillity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('visibillity', postgresql.ENUM('public', 'private', 'draft', name='visibillity'), autoincrement=False, nullable=True))
    op.drop_column('works', 'visibility')
    op.drop_column('user', 'github_id')
    op.drop_column('user', 'twitter_id')
    # ### end Alembic commands ###
