"""init database

Revision ID: f03c01296e25
Revises: 
Create Date: 2022-11-21 16:47:42.996758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f03c01296e25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(length=32), nullable=False),
    sa.Column('discord_token', sa.String(), nullable=True),
    sa.Column('discord_refresh_token', sa.String(), nullable=True),
    sa.Column('discord_user_id', sa.String(length=18), nullable=True),
    sa.Column('profile', sa.String(length=500), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('twitter_id', sa.String(), nullable=True),
    sa.Column('github_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('token',
    sa.Column('refresh_token', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('refresh_token')
    )
    op.create_table('works',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('description_html', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('visibility', sa.Enum('public', 'private', 'draft', name='visibility'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('work_id', sa.String(length=255), nullable=True),
    sa.Column('asset_type', sa.Enum('zip', 'image', 'video', 'music', 'model', name='assettype'), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('extension', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('work_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('reply_at', sa.String(), nullable=True),
    sa.Column('visibility', sa.Enum('public', 'private', 'draft', name='visibility'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite',
    sa.Column('work_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('work_id', 'user_id')
    )
    op.create_table('taggings',
    sa.Column('work_id', sa.String(length=255), nullable=False),
    sa.Column('tag_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('work_id', 'tag_id')
    )
    op.create_table('urlinfo',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('work_id', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('url_type', sa.Enum('youtube', 'soundcloud', 'github', 'sketchfab', 'unityroom', 'other', name='urltype'), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thumbnails',
    sa.Column('work_id', sa.String(length=255), nullable=False),
    sa.Column('asset_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('work_id', 'asset_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thumbnails')
    op.drop_table('urlinfo')
    op.drop_table('taggings')
    op.drop_table('favorite')
    op.drop_table('comment')
    op.drop_table('asset')
    op.drop_table('works')
    op.drop_table('token')
    op.drop_table('user')
    op.drop_table('tags')
    # ### end Alembic commands ###
