version: '3.9'
services:
  db:
    image: postgres:13.3-buster
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - .env

  api:
    build: 
      context: ../
      dockerfile: .devcontainer/Dockerfile
    # command: pipenv run uvicorn main:app --host 0.0.0.0 --reload
    command: sleep infinity
    volumes:
      - ../:/api
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on: 
      - db

volumes: 
  dbdata:
