name: Lint

on:
  push:

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.12
          architecture: x64
      - name: Checkout
        uses: actions/checkout@master
      - name: Install flake8
        run: pip install flake8
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          ignore: 'E302, E305, W605'
          exclude: 'tests/*'
          max-line-length: 200
          path: '.'
